### ISSUE TITLE
Revisão - UML da arquitetura de camadas

### ISSUE THREAD

**Issue by Jlmsousa** [fga-eps-mds/2023.1-NEXUS-hub-fga-inovacao#43]
Após a primeira release que ocorreu no dia 09/05/2023, a professora Carla em conjunto com o monitor Leonardo realizaram criticas construtivas a respeito da arquitetura de camadas desenvolvida pelo nosso grupo. Os próximos passos para a nova arquitetura de camadas serão:

- [x] Rever os apontamentos realizados pela professora e pelo monitor;
- [x] Conversar com a nossa monitora Mylena;
- [x] Refazer a arquitetura de camadas;
- [x] Realizar uma revisão em equipe;
- [x] Enviar a nova arquitetura para a pasta "documentação" deste repositório.

**Comment by The-Boss-Nina** [comment]
A professora, nos passou a imagem com as anotações realizadas por ela sobre a apresentação da nossa "1ª Release" que ocorreu no dia 9 de maio.

![Anotação da Prof - Grupo 4](https://github.com/fga-eps-mds/2023.1-NEXUS-hub-fga-inovacao/assets/58699832/398ba5d6-b5b1-46cd-a221-dbbebfc5ec68)

**Comment by The-Boss-Nina** [comment]
Conversamos com a nossa monitora Mylena e realizamos algumas mudanças na camada de "Dados" da nossa "Arquitetura em Camadas", resultando em uma nova arquitetura.

![Arquitetura em Camadas (1)](https://github.com/fga-eps-mds/2023.1-NEXUS-hub-fga-inovacao/assets/58699832/ece90d1f-844d-4541-b29a-18bd50a3b495)
