### ISSUE TITLE
Criação do código de raspagem de dados dos professores para melhorar eficiência

### ISSUE THREAD

**Issue by The-Boss-Nina** [fga-eps-mds/2023.1-NEXUS-hub-fga-inovacao#46]
Descrição da issue:

• Atualmente, temos que criar um código de raspagem de dados dos professores da Universidade de Brasília - Campus Gama (FGA). A tarefa consiste em criar um código de maneira eficiente eficiente e de fácil entendimento.

Principais pontos a serem considerados na criação:

- [x] Criação da estrutura geral do código: criar um código de raspagem que consiste em coletar os dados relativos aos professores da FGA;

- [x]  Revisar a estrutura geral do código: analisar a organização do código e identificar possíveis melhorias na estrutura, como modularização, separação de responsabilidades e utilização de funções auxiliares;

- [x] Trabalhar com o tratamento de possíveis erros: verificar se o código atual lida corretamente com possíveis erros, como conexões falhadas, respostas vazias ou incorretas, e implementar mecanismos adequados para tratá-los de forma robusta;

- [x] Aprimorar a legibilidade e manutenibilidade: rever o código para torná-lo mais legível e facilitar a manutenção. Isso inclui a utilização de nomes de variáveis e funções descritivas, comentários claros e concisos, e formatação adequada;

- [x] Testar o código: criar casos de teste para verificar se o código está produzindo os resultados esperados.

Isso ajudará a garantir que as alterações não tenham introduzido erros ou quebras de funcionalidades.

Lembre-se de documentar adequadamente as alterações realizadas, explicando os motivos por trás de cada decisão.

Caso tenha alguma dúvida ou precise de mais informações, sinta-se à vontade para perguntar.

**Comment by Jlmsousa** [comment]
Utilizamos os princípios de XP (Extreme Programming), onde alternamos entre piloto e co-piloto na execução das tarefas descritas acima.
